---
version: '3.7'
services:
  apache-ignite-inmemory-cache-node-1:
    mem_reservation: "1.5G"
    mem_limit: "1.5G"
    image: applem1support/ignite:2.12.0
    hostname: ignite-inmemory-cache-node-1
    restart: on-failure
    environment:
      JVM_OPTS: "-server -Xms1100m -Xmx1100m -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC -XX:MaxDirectMemorySize=1100m"
    entrypoint:
      - bash
      - -c
      - |
        cd /opt/ignite/apache-ignite
        cp -R libs/optional/ignite-zookeeper libs/
        ./run.sh
    ports:
      - "0.0.0.0:10800:10800"
      - "0.0.0.0:25000:25000"
    volumes:
      - ./conf/default-ignite-config-node-1.xml:/opt/ignite/apache-ignite/config/default-config.xml:ro
  apache-ignite-inmemory-cache-node-2:
    mem_reservation: "1.5G"
    mem_limit: "1.5G"
    image: applem1support/ignite:2.12.0
    hostname: ignite-inmemory-cache-node-2
    restart: on-failure
    environment:
      JVM_OPTS: "-server -Xms1100m -Xmx1100m -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC -XX:MaxDirectMemorySize=1100m"
    entrypoint:
      - bash
      - -c
      - |
        cd /opt/ignite/apache-ignite
        cp -R libs/optional/ignite-zookeeper libs/
        ./run.sh
    ports:
      - "0.0.0.0:10810:10810"
      - "0.0.0.0:25001:25001"
    volumes:
      - ./conf/default-ignite-config-node-2.xml:/opt/ignite/apache-ignite/config/default-config.xml:ro
  apache-ignite-inmemory-cache-node-3:
    mem_reservation: "1.5G"
    mem_limit: "1.5G"
    image: applem1support/ignite:2.12.0
    hostname: ignite-inmemory-cache-node-3
    restart: on-failure
    environment:
      JVM_OPTS: "-server -Xms1100m -Xmx1100m -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC -XX:MaxDirectMemorySize=1100m"
    entrypoint:
      - bash
      - -c
      - |
        cd /opt/ignite/apache-ignite
        cp -R libs/optional/ignite-zookeeper libs/
        ./run.sh
    ports:
      - "0.0.0.0:10820:10820"
      - "0.0.0.0:25002:25002"
    volumes:
      - ./conf/default-ignite-config-node-3.xml:/opt/ignite/apache-ignite/config/default-config.xml:ro